language: rust
sudo: required
rust:
  - nightly
addons:
  postgresql: '9.5'
before_script:
  - cargo install diesel_cli
  - diesel setup
  - export DATABASE_URL=postgres://postgres@localhost/
  - psql -c "create database test;" -U postgres
  - psql -c "create role ${USER} superuser createdb nocreaterole inherit login;" -U postgres
branches:
  only:
    - master