language: rust
sudo: required
rust:
  - nightly
cache: cargo
addons:
  postgresql: '9.4'
before_script:
  - export DATABASE_URL=postgres://postgres@localhost/
  - psql -c "create database test;" -U postgres
branches:
  only:
    - master
