language: rust
sudo: required
rust:
  - nightly
cache: cargo
addons:
  postgresql: '9.4'
before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - (cargo install diesel_cli || true)
  - diesel setup
  - export DATABASE_URL=postgres://postgres@localhost/
  - psql -c "create database test;" -U postgres
branches:
  only:
    - master
