[package]
name = "personal-website"
version = "0.1.0"
authors = ["Krishan Wyse <kwysek@gmail.com>"]
build = "build.rs"

[dependencies]
log = "*"
fern = "*"
chrono = "*"
iron = "*"
router = "*"
mount = "*"
staticfile = "*"
handlebars-iron = "*"
hoedown = "*"
rustc-serialize = "*"

[build-dependencies]
sass-rs = "*"

[target.heroku]
version = "nightly"
