baseURL = "https://www.kwyse.com/"
languageCode = "en-gb"
defaultLanguageContent = "en"
title = "The Blog of Krishan Wyse"
theme = "hermit"

pygmentsCodefences  = true
pygmentsUseClasses  = true

[author]
  name = "Krishan Wyse"

[params]
  dateform        = "2 Jan 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02"

  homeSubtitle = "life.iter().map(Musings::fetch).collect()"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/KrishanWyse"

  [[params.social]]
    name = "github"
    url = "https://github.com/kwyse/"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/krishanwyse/"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "CV"
    url = "cv/"
    weight = 10
