baseURL = "http://www.kwyse.com/"
theme = "minimo"
title = "Krishan Wyse"
languageCode = "en-us"

defaultContentLanguage = "en"
sectionPagesMenu = "main"

pygmentsCodefences = true
Paginate = 10
disqusShortname = "kwyse"

googleAnalytics = "UA-112072110-1"

[languages.en]
lang = "en"
language = "English"
weight = 1

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -1

[params.assets]
customCSS = [ "custom.css" ]

[params.copyright]
prefix = ""
holder = "Krishan Wyse"
startYear = "2017"
suffix = ""

[params.info]
description = "life.iter().map(Musings::fetch).collect()"
title404 = "Nothing's here!"

[params.settings]
dateFormat = "02 Jan 2006"
listDateFormat = "02 Jan 2006"
recentPostsLength = 5
showReadingTime = true
noTermCloudShuffle = true
accentColor = "#1793d0"

[params.social]
email = "contact@kwyse.com"
github = "kwyse"
linkedin = "krishanwyse"
twitter = "KrishanWyse"
[params.social.config]
platforms = ["linkedin", "twitter", "github", "email"]

[params.widgets]
homepage = ["recent_posts", "taxonomy_cloud"]

[taxonomies]
category = "categories"
tags = "tags"
series = "series"
